<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Li Europan lingues (en)_radioTextname</name>
   <tag></tag>
   <elementGuidId>76600307-9266-4430-a0bd-dec55fbbf841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idRadioTextname-EN-far-away-behind']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idRadioTextname-EN-far-away-behind</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd8ca85f-169b-4538-846b-4ee36b97b076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idRadioTextname-EN-far-away-behind</value>
      <webElementGuid>e7ca60c0-9867-472d-a6d8-eef14484037b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-textname iradio</value>
      <webElementGuid>89db2106-30c9-4183-b955-87f5a484aba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d378ac72-474a-45e5-a7b7-b866aaf2b104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioTextname</value>
      <webElementGuid>2e61f04c-4bc9-471a-bdfe-720c812b7d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>e20244d2-cd47-4f81-bba8-d79f7b1d2e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idRadioTextname-EN-far-away-behind&quot;)</value>
      <webElementGuid>768d05f5-c9d2-4b3d-a4c6-5f663fda7f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c49aa18d-20e9-486e-be18-88cac01edd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idRadioTextname-EN-far-away-behind</value>
      <webElementGuid>7db131f5-b8d9-45f8-9d3e-1d62e27f5cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-textname iradio</value>
      <webElementGuid>f78c5143-4b28-4028-93b7-70ca3fa2b493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f01e32aa-6e1e-4e92-8195-0d9de1815a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioTextname</value>
      <webElementGuid>f2c7b701-868a-4cef-9c4b-030502e60fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>44a6416a-78f7-4608-afce-1381bdea4af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idRadioTextname-EN-far-away-behind&quot;)</value>
      <webElementGuid>daccbfc8-4c1b-43e0-a8fa-9390a1e05872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idRadioTextname-EN-far-away-behind']</value>
      <webElementGuid>725fd49d-0846-468e-8d5d-f4af7c6d1d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='idTextname']/input[6]</value>
      <webElementGuid>ad655ded-d0a7-40d2-b4b6-e654955a45b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>f9cd5673-fe63-4efc-af55-cafc8d5adb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idRadioTextname-EN-far-away-behind' and @type = 'radio' and @name = 'radioTextname']</value>
      <webElementGuid>a2bf4c96-b009-49a0-8bde-f8c932e5e724</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
