<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number_idInputWords</name>
   <tag></tag>
   <elementGuidId>8ca2db80-a5fc-441d-ad09-0d262c1900b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idInputWords']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idInputWords</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41bbee35-9a42-4620-a8b2-9e7f20e2befb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idInputWords</value>
      <webElementGuid>1bd8c0c9-87f2-4dae-af44-03410aad5bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>itext_short mb_10</value>
      <webElementGuid>97b81c03-ca4e-4462-89f7-cbce00796cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3896271e-d378-461d-a7ac-8e1084fc31b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>b124bc05-e8f8-443a-9cda-8b0160aa6681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idInputWords&quot;)</value>
      <webElementGuid>ca226873-5f6f-450e-9646-6018ab31743e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5faeefbe-fb93-42c5-903f-ff07f35f1f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idInputWords</value>
      <webElementGuid>19f53ef5-dcd4-4aca-8b5a-e8da7a549858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>itext_short mb_10</value>
      <webElementGuid>ac0b6023-125d-4845-9ead-82ead5050498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdf79de3-78a0-4a8e-8aa1-bf225c0f940d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>7264526d-4b6b-43db-8bbb-e7e28795b8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idInputWords&quot;)</value>
      <webElementGuid>d6e9c3c1-6fc4-41a2-b5f3-430548517780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idInputWords']</value>
      <webElementGuid>c0f852d3-9ca9-423a-8b7c-2da379e8472f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/form/fieldset/fieldset[2]/input</value>
      <webElementGuid>452bba0a-bf28-467e-aad5-29562b29a5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/input</value>
      <webElementGuid>485f4240-0191-4174-970e-2bb4755f07f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idInputWords' and @type = 'text']</value>
      <webElementGuid>3498cc63-ffdc-44ee-a6de-4c5e6af90f7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
